name: vishwajit-vishnu's Archive
title: vishwajit-vishnu's Archive | A Tech Blog
description: 풀 스택이 되고자 하는 학생의 꾸준하고 싶은 기록입니다.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: vishwajit-vishnu@naver.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
